#Copyright (c) 2022 All project authors. All rights reserved.
#
#This source code is licensed under Apache 2.0 License.

server:
  port: 8083

nebula:
  hosts: 172.16.41.143:9669
  username: root
  password: nebula
  space: test
  pool-config:
    min-conns-size: 0
    max-conns-size: 10
    timeout: 6000
    idle-time: 0
    interval-idle: -1
    wait-time: 6000
    min-cluster-health-rate: 1.0
    enable-ssl: false

logging:
  level:
    org:
      nebula:
        contrib: DEBUG