#Copyright (c) 2022 All project authors. All rights reserved.
#
#This source code is licensed under Apache 2.0 License.

server:
  port: 8083

nebula:
  hosts: 127.0.0.1:19669
  username: root
  password: nebula
  space: test
  pool-config:
    min-conns-size: 0
    max-conns-size: 10
    timeout: 6000
    idle-time: 0
    interval-idle: -1
    wait-time: 6000
    min-cluster-health-rate: 1.0
    enable-ssl: false